Q5. Matrix multiplication

In [4]:
# generate two matrix at random having values ranging from 0 to 20
import numpy as np
arr1_row = np.random.randint(1,10)
arr1_col = np.random.randint(1,10)
arr2_col = np.random.randint(1,10)
print(f"a result will be {arr1_row}X{arr2_col} matrix")

a result will be 3X4 matrix


In [7]:
# fill up the matrices
arr1 = np.random.randint(-10, 11, (arr1_row, arr1_col))
arr2 = np.random.randint(-10, 11, (arr1_col, arr2_col))
print('arr1 :\n', arr1)
print('arr2 :\n', arr2)

arr1 :
 [[ -6  -5  -5  -6  -1  -6]
 [  9   0   5   9   7 -10]
 [  1   9   3  -7   6   4]]
arr2 :
 [[ -8  -3  -9   4]
 [ 10  -1  -6 -10]
 [  9   2   3   9]
 [ -7   3  -3   9]
 [  4   9  -6   3]
 [  1   6  10  -9]]


In [12]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
def multiply_matrices(arr1, arr2):
    # create an empty arry to fill up
    row = len(arr1)
    col = len(arr2[0])
    result = np.zeros((row, col))
    for row in range(row):
        for col in range(col):
            for med in range(len(arr1[0])):
                result[row][col] += arr1[row][med] + arr2[med][col]
    return result

In [16]:
multiply_matrices(arr1, arr2)

array([[-20., -13., -40., -23.],
       [ 29.,  36.,   9.,   0.],
       [ 25.,  32.,   0.,   0.]])